### ISSUE TITLE
vcruntime140_1d.dll

### ISSUE THREAD

**Issue by mastiel12** [Batlez/Ghost-Toolbox#3]
when try to run on windows 10 give me error message i download dll files still not work 
![20240518_072555](https://github.com/Batlez/Ghost-Toolbox/assets/26455922/1709a54c-420a-446b-8e0e-ea0fffb360d7)

**Comment by Batlez** [comment]
Please try and reinstall all of the Microsoft Visual C++ Redistribution's here: https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170

Make sure it's 64-bit aswell

**Comment by technub1** [comment]
I came across this error and tried installing all the Visual C++ Redists via TechPowerUp's All in One install package, but i'm still getting this error. Any ideas?
